# model-definition.yml

kind: Model
apiVersion: v1alpha4

metadata:
  displayName: UDM Setup
  name: udm-setup
  summary: Allows for data preparation for inputs into the full UDM model.
  description: >
    The model allow for vector data to be rasterized to a common fishnet/grid as required for inputs into the UDM (Urban
    Development model). Data to be rasterized can be supplied as vector files (.geojson, .gpkg) and using the same input
    grid, supplied in a similar vector format (.geojson, .gpkg), will each be output as rasters (as .tif).

    Further updates will add additional features including using data from NISMOD-DB API to generate a fishnet to be used
    and also for the input vector data to be rasterized.
  type: data-processing

spec:
  inputs:
    env:
      - name: INITIAL_POPULATION
        title: Initial population
        desc: The initial population in the area
        type: int
        default: 10
        min: 0
      - name: NEW_DWELLINGS
        title: New dwellings
        desc: The number of new dwellings to place in the area
        type: int
        default: 10
        min: 0
    dataslots:
      - name: attractor definition(s)
          description: >
            A .csv file which defines the attractor layers and their weight
          default:
            - uid:
              versionUid:
          path: inputs/attractor_csv
          required: true
      - name: constraint definition(s)
          description: >
            A .csv file which defines the constraint layers and their weight
          default:
            - uid:
              versionUid:
          path: inputs/constraint_csv
          required: true
      - name: attractor datasets
          description: >
            A set of files as defined in the attractor definition file
          default:
            - uid:
              versionUid:
          path: inputs/attractors
          required: true
      - name: constraint datasets
          description: >
            A set of files defined in the constraint definition file
          default:
            - uid:
              versionUid:
          path: inputs/constraints
          required: true
      - name: new settlement locations
          description: >
            A .csv file which defines the locations of new settlements
          default:
            - uid:
              versionUid:
          path: inputs/settlement_csv
          required: true
      - name: Fishnet
        description: >
          A grid/fishnet vector format file (.geojson, .gpkg)
        default:
          - uid: d37c7218-4f3d-44eb-8a4c-8ad08bbe5d20
            versionUid: 9aab4978-a60a-41bc-a36e-f8752f989d59
        path: inputs/fishnet
        required: false
      - name: Features
        description: >
          A file containing vector features to rasterize (.geojson, .gpkg)
        default:
          - uid: 787e608f-f435-426f-8e2a-054dac8fc10e
            versionUid: 7f6182ba-60b2-4ef9-bfa0-e6c8eae64aee
        path: inputs/vectorfiles
        required: false

  outputs:
    datasets:
      - name: UDM model run fileset
        desc: Set of files required for running the UDM model
